<a href="https://colab.research.google.com/github/NishaSathish/Consolidated_code_for_activity_tracking/blob/nisha_master/Copy_of_Consolidated_code_for_activity_tracking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset

In [2]:
dataset = pd.read_csv('sensor_activity_training_dataset.csv')

In [3]:
print (dataset)

       feature_1  feature_2  feature_3  ...  feature_399  feature_400  activity
0          0.281   -0.00996    -0.1060  ...       -0.999       -0.999       5.0
1          0.277   -0.01270    -0.1030  ...       -0.999       -0.999       5.0
2          0.276   -0.02140    -0.1080  ...       -1.000       -1.000       5.0
3          0.278   -0.02040    -0.1130  ...       -1.000       -1.000       5.0
4          0.277   -0.01470    -0.1070  ...       -1.000       -1.000       5.0
...          ...        ...        ...  ...          ...          ...       ...
10232      0.310   -0.05340    -0.0991  ...       -0.947       -0.929       2.0
10233      0.363   -0.03920    -0.1060  ...       -0.925       -0.836       2.0
10234      0.350    0.03010    -0.1160  ...       -0.933       -0.877       2.0
10235      0.238    0.01850    -0.0965  ...       -0.960       -0.923       2.0
10236      0.154   -0.01840    -0.1370  ...       -0.980       -0.954       2.0

[10237 rows x 401 columns]


#data preprocessing

#searching for empty rows and dropping them

In [4]:
dataset.isnull()
dataset_train = dataset.dropna(how = 'all')
print (dataset_train)

       feature_1  feature_2  feature_3  ...  feature_399  feature_400  activity
0          0.281   -0.00996    -0.1060  ...       -0.999       -0.999       5.0
1          0.277   -0.01270    -0.1030  ...       -0.999       -0.999       5.0
2          0.276   -0.02140    -0.1080  ...       -1.000       -1.000       5.0
3          0.278   -0.02040    -0.1130  ...       -1.000       -1.000       5.0
4          0.277   -0.01470    -0.1070  ...       -1.000       -1.000       5.0
...          ...        ...        ...  ...          ...          ...       ...
10232      0.310   -0.05340    -0.0991  ...       -0.947       -0.929       2.0
10233      0.363   -0.03920    -0.1060  ...       -0.925       -0.836       2.0
10234      0.350    0.03010    -0.1160  ...       -0.933       -0.877       2.0
10235      0.238    0.01850    -0.0965  ...       -0.960       -0.923       2.0
10236      0.154   -0.01840    -0.1370  ...       -0.980       -0.954       2.0

[10224 rows x 401 columns]


#Dimensionality reduction

#missing value ratio

In [5]:
missing_value = dataset_train.isnull().sum()/len(dataset_train)*100


variables = dataset_train.columns
variable = [ ]
for i in range(0,400):
    if missing_value[i]>=20:   #setting the threshold as 20%
        variable.append(variables[i])


#low variance filter.

In [6]:
var = dataset_train.var()*100

numeric = dataset_train.columns
variable = [ ]
len(var)
for i in range(0,400):
    if var[i]<=5:   #setting the threshold as 5%
       variable.append(numeric[i]) 

# Drop features 

In [7]:
dataset_train = dataset_train.drop(dataset_train[variable], axis=1)

In [8]:
print(dataset_train)

       feature_4  feature_5  feature_6  ...  feature_396  feature_398  activity
0         -0.995    -0.9730     -0.986  ...       -1.000       -0.999       5.0
1         -0.995    -0.9730     -0.985  ...       -1.000       -0.999       5.0
2         -0.998    -0.9870     -0.993  ...       -1.000       -1.000       5.0
3         -0.999    -0.9850     -0.996  ...       -1.000       -1.000       5.0
4         -0.999    -0.9910     -0.993  ...       -1.000       -1.000       5.0
...          ...        ...        ...  ...          ...          ...       ...
10232     -0.288    -0.1410     -0.215  ...       -0.724       -0.912       2.0
10233     -0.305     0.0281     -0.196  ...       -0.754       -0.877       2.0
10234     -0.330    -0.0421     -0.250  ...       -0.735       -0.896       2.0
10235     -0.323    -0.2300     -0.208  ...       -0.763       -0.965       2.0
10236     -0.330    -0.1950     -0.164  ...       -0.751       -0.963       2.0

[10224 rows x 280 columns]


# dependent and independent variable set

In [9]:
X_train = dataset_train.iloc[:, :279].values
y_train = dataset_train.iloc[:, 279].values

#Dimensionality Reduction PCA

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 10)
X_train = pca.fit_transform(X_train)
explained_variance = pca.explained_variance_ratio_

#Dimensionality Reduction LDA

In [10]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 5)
X_train = lda.fit_transform(X_train, y_train)

#Training the logistic regression model on the training dataset

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

#Training the Kernel SVM model on the training dataset

In [ ]:
from sklearn.svm import SVC
classifier = SVC(C = 1, kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train )

#Training the KNN model on the training dataset

In [11]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 15, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=15, p=2,
                     weights='uniform')

#Training the SVM model on the training dataset

In [ ]:
from sklearn.svm import SVC
classifier = SVC(C=0.5, kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train )

#Training the Naive bayes classifier on the training dataset

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

#Training the Decision Tree classifier on the training dataset

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

#Training the Random forest classifier on the training dataset

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 15, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

#Training XGBoost on the training set

In [11]:
import xgboost as xgb
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

#Applying k-Fold Cross Validation

In [12]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 5)
print("Accuracy: {:.2f} %".format (accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format (accuracies.std()*100))

Accuracy: 97.61 %
Standard Deviation: 0.65 %


#prediction of test results

#Importing the dataset

In [13]:
dataset_test = pd.read_csv('sensor_activity_testing_dataset.csv')

#dropping the columns same as training dataset
Drop features 

In [14]:
dataset_test = dataset_test.drop(dataset_test[variable], axis=1)
print (dataset_test)





    feature_4  feature_5  feature_6  ...  feature_396  feature_398  activity ACTUAL
0      -0.995     -0.983     -0.914  ...         -1.0       -1.000                5
1      -0.998     -0.975     -0.960  ...         -1.0       -0.999                5
2      -0.995     -0.967     -0.979  ...         -1.0       -1.000                5
3      -0.996     -0.983     -0.991  ...         -1.0       -1.000                5
4      -0.998     -0.981     -0.990  ...         -1.0       -1.000                5
..        ...        ...        ...  ...          ...          ...              ...
70     -0.991     -0.956     -0.981  ...         -1.0       -0.999                4
71     -0.990     -0.949     -0.978  ...         -1.0       -1.000                4
72     -0.991     -0.920     -0.980  ...         -1.0       -1.000                4
73     -0.989     -0.947     -0.977  ...         -1.0       -0.998                4
74     -0.973     -0.938     -0.967  ...         -1.0       -0.995          

In [15]:
X_test = dataset_test.iloc[:, :279].values
y_test = dataset_test.iloc[:, 279].values

#Dimensionality reduction for the test dataset

In [16]:
X_test = lda.transform(X_test)



#Predicting the Test set results

In [17]:
y_pred = classifier.predict(X_test)
print (y_pred)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 5. 5.]


#Confusion matrix

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[13  0  0  0  0  0]
 [ 0 14  0  0  0  0]
 [ 0  0 12  0  0  0]
 [ 0  0  0 13  2  0]
 [ 0  0  0  0  9  0]
 [ 0  0  0  0  0 12]]


0.9733333333333334